# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RunoLog
description: > # this means to ignore newlines until "baseurl:"
  deraruのブログ。技術系の記事や旅行記、自分の考えなどを書いています。
author: deraru
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.deraru.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: deraru
twitter_username: deraru
google_analytics: UA-25908311-1

# Build settings
markdown: kramdown
theme: minima
lang: ja
plugins:
  - jekyll-feed
exclude:
  - node_modules
  - src
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - webpack.config.js
  - yarn.lock
